lib: [
  "_build/install/default/lib/labwork2/META"
  "_build/install/default/lib/labwork2/dune-package"
  "_build/install/default/lib/labwork2/labwork2.a"
  "_build/install/default/lib/labwork2/labwork2.cma"
  "_build/install/default/lib/labwork2/labwork2.cmi"
  "_build/install/default/lib/labwork2/labwork2.cmt"
  "_build/install/default/lib/labwork2/labwork2.cmti"
  "_build/install/default/lib/labwork2/labwork2.cmx"
  "_build/install/default/lib/labwork2/labwork2.cmxa"
  "_build/install/default/lib/labwork2/labwork2.ml"
  "_build/install/default/lib/labwork2/labwork2.mli"
  "_build/install/default/lib/labwork2/labwork2__.cmi"
  "_build/install/default/lib/labwork2/labwork2__.cmt"
  "_build/install/default/lib/labwork2/labwork2__.cmx"
  "_build/install/default/lib/labwork2/labwork2__.ml"
  "_build/install/default/lib/labwork2/labwork2__Rb_dict.cmi"
  "_build/install/default/lib/labwork2/labwork2__Rb_dict.cmt"
  "_build/install/default/lib/labwork2/labwork2__Rb_dict.cmti"
  "_build/install/default/lib/labwork2/labwork2__Rb_dict.cmx"
  "_build/install/default/lib/labwork2/labwork2__Rb_tree.cmi"
  "_build/install/default/lib/labwork2/labwork2__Rb_tree.cmt"
  "_build/install/default/lib/labwork2/labwork2__Rb_tree.cmti"
  "_build/install/default/lib/labwork2/labwork2__Rb_tree.cmx"
  "_build/install/default/lib/labwork2/opam"
  "_build/install/default/lib/labwork2/rb_dict.ml"
  "_build/install/default/lib/labwork2/rb_dict.mli"
  "_build/install/default/lib/labwork2/rb_tree.ml"
  "_build/install/default/lib/labwork2/rb_tree.mli"
]
libexec: [
  "_build/install/default/lib/labwork2/labwork2.cmxs"
]
bin: [
  "_build/install/default/bin/labwork2_cli"
]
doc: [
  "_build/install/default/doc/labwork2/README.md"
]
