name: Deploy coverage info to Pages

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tree
        uses: actions/checkout@v5

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 4.14.2

      - name: Install deps (tests & dev)
        run: |
          opam update
          opam install dune -y
          opam install . --deps-only --with-test -y
          opam install bisect_ppx ounit2 qcheck qcheck-ounit -y

      - name: Run tests with coverage
        run: opam exec -- dune runtest --instrument-with bisect_ppx

      - name: Build coverage HTML
        run: opam exec -- bisect-ppx-report html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: '_coverage/'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
